### PR TITLE
Update futures and wasm-bindgen-futures deps

### PR DESCRIPTION
**Pull request by Hamza12700**

### CODE REVIEW

**Review by tomka — APPROVED** [review]
Thanks a lot, this looks good to me!

**Comment by tomka** [comment]
Why the WIP/draft status?

**Comment by Hamza12700** [comment]
Fix a lot of compiler errors related to async code in `lib.rs` and `http_fetch.rs` files.

The only thing left to fix is the custom marco `data_type_match`, but everything else compiles just fine.

**Review by tomka — APPROVED** [review]
Thanks, these changes look good to me.

**Pull request merged**
